# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=500)),
                ('blog_id', models.ForeignKey(db_column='blog_id', on_delete=django.db.models.deletion.CASCADE, to='lucumr.Blog')),
            ],
            options={
                'managed': True,
                'db_table': 'tags',
            },
        ),
    ]
